## RLHF PPO Training

## ScriptArguments
model_name: "meta-llama/Llama-3.1-8B-Instruct"        ## 사용할 모델명 (huggingface model name)
adapter_name: "adapter/Zip-Llama-sft-v1.0.0"
dataset_path: "./data"                                ## 데이터셋 저장 경로
rm_name: "adapter/RM-Llama-v1.0.1"
max_length: 16384

## PPOConfig
response_length: 512                                  ## 모델 생성 최대 길이
stop_token: "eos"                                     ## 토크나이저의 eos 토큰을 생성 종료 토큰으로 설정
output_dir: "./results/ppo-v1.0.1.0"                  ## 튜닝된 모델 저장 위치
report_to: "wandb"                                    ## 튜닝 로그 리포트 (토큰 등록 필요)
run_name: "ppo-v1.0.1.0"
learning_rate: 1e-6                                   ## update matrix 학습률
lr_scheduler_type: "cosine_with_min_lr"               ## 코사인 스케줄러 사용 + 최소 학습률 지정 (최대의 10%)
lr_scheduler_kwargs:
  min_lr_rate: 0.1
per_device_train_batch_size: 2                        ## GPU당 배치 사이즈
per_device_eval_batch_size: 2                         ## GPU당 배치 사이즈(평가)
gradient_accumulation_steps: 16                       ## 그래디언트를 모아두었다가 한꺼번에 적용: 배치 사이즈를 키우는 효과
do_eval: true                                         ## evaluation loss 계산 (전체 eval dataset을 대상으로 산출하므로, 꽤 많은 시간이 소요됨.)
eval_steps: 0.0625
eval_strategy: "steps"                                 ## 일정 스탭마다 모델 평가
optim: "adamw_torch_fused"                            ## optimizer 설정
logging_steps: 0.03125
logging_strategy: "steps"                             ## 에폭별 로그 산출
save_strategy: "steps"                                ## 일정 스탭마다 모델 저장
save_steps: 0.0625
weight_decay: 0.01                                    ## adamw optimizer에서 l2-norm weight decay. 과적합 방지.
max_grad_norm: 0.5                                    ## 그래디언트 클리핑의 임계값 지정. 모든 파라미터의 그래디언트에 대하여 l2-norm의 임계값. exploding 방지. 낮게 설정하면 훈련 속도 느려질 수 있음.
warmup_ratio: 0.03                                    ## 초기 학습률 warmup 단계의 비중 설정: 총 스텝 중 비율. 데이터셋과 모델 크기에 따라 조정. (모델와 데이터셋이 클수록 warmup_step을 키워주면 효과적)
bf16: true                                            ## bf16 정밀도 활성화: 모델 내부 연산 수행
tf32: true                                            ## nvidia TensorFormat-32 활성화: fp32로 수행되어야 하는 일부 연산을 가속
gradient_checkpointing: true                          ## 버그때문에 코드에서 켜야됨
dataloader_num_workers: 2                             ## 데이터로더 워커 수: 보통 GPU 개수 * 4 정도 사용한다고 함
push_to_hub: false                                    ## 허깅페이스에 모델 로드
missing_eos_penalty: 1.0                              ## max_token_size를 초과하여 생성함으로써 eos 토큰으로 끝나지 않는 경우 패널티 부여(완결성 보완)
kl_coef: 0.02                                         ## kl divergence term coef
total_episodes: 10240                                 ## 에피소드 수 (1개 프롬프트가 상호작용하면 1 에피소드)
num_ppo_epochs: 1                                     ## 한 번 수집한 버퍼 데이터를 몇 번 반복하여 학습할 것인지 (1로 설정하여 과적합 방지)
local_rollout_forward_batch_size: 8                   ## 생성 버퍼 배치 크기
num_mini_batches: 1                                   ## 갱신에 사용하는 배치 크기
